spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?currentSchema=public
    driverClassName: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  jackson:
    time-zone: Asia/Novosibirsk
    date-format: dd.MM.yyyy HH:mm:ss

server:
  port: ${SERVER_PORT}
  address: ${SERVER_ADDRESS:0.0.0.0}
  error:
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  timezone: Asia/Novosibirsk