spring:
  datasource:
    url: ${DB_URL}
    driverClassName: ${DB_DRIVER}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

server:
  port: ${SERVER_PORT:8081}
  address: ${SERVER_ADDRESS:0.0.0.0}

еgoogle:
  sheets:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8081/api/v1/auth/google/callback}
    scopes: https://www.googleapis.com/auth/spreadsheets

logging:
  level:
    org.springframework.security: DEBUG